apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: web
         image: 494013786575.dkr.ecr.us-east-1.amazonaws.com/hellogo:latest
         ports:
          - containerPort: 8080